import Link from "next/link";
import { FaGithub, FaGraduationCap } from "react-icons/fa6";

export default function ProjectEdugen() {
  return (
    <article className="document project-document">
      <header className="document-header">
        <div>
          <span className="doc-kicker">EDTECH &amp; GENERATIVE AI</span>
          <h1>EduGen Quiz Generator</h1>
        </div>
        <span className="ink-stamp gold">AI</span>
      </header>

      <p className="lead">
        An AI-powered automated assessment engine that generates structured quizzes, questions, answer evaluations, and personalized study feedback across multiple difficulty tiers.
      </p>

      <div className="project-visual" style={{ background: "linear-gradient(135deg, #2b1055, #7597de)", display: "flex", alignItems: "center", justifyContent: "center", gap: "20px" }}>
        <div style={{ textAlign: "center", color: "white" }}>
          <div style={{ display: "inline-flex", padding: "16px", borderRadius: "50%", background: "var(--red)", marginBottom: "8px" }}>
            <FaGraduationCap size={36} color="white" />
          </div>
          <p style={{ margin: 0, fontFamily: "var(--pixel)", fontSize: "11px", letterSpacing: "1px" }}>DYNAMIC AI QUIZ GENERATOR</p>
        </div>
        <div className="scan-line" />
      </div>

      <div className="doc-grid">
        <section>
          <h3>Capabilities</h3>
          <ul>
            <li>
              <strong>Instant Assessment Creation:</strong> Transforms topics, textbook snippets, or learning objectives into comprehensive quizzes.
            </li>
            <li>
              <strong>Scoring &amp; Reasoning:</strong> Explains right and wrong options with clear step-by-step reasoning generated by LLMs.
            </li>
            <li>
              <strong>Modern UI/UX:</strong> Fast and responsive interface allowing students and educators to generate and take quizzes interactively.
            </li>
          </ul>
        </section>

        <aside>
          <h3>Tech Stack</h3>
          <div className="doc-tags">
            <span>JavaScript</span>
            <span>React.js</span>
            <span>Node.js</span>
            <span>LLM Integration</span>
            <span>REST API</span>
          </div>

          <Link
            className="doc-link"
            href="https://github.com/231B121/-Edugen-Quiz-Generator-"
            target="_blank"
            rel="noreferrer"
            style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}
          >
            <FaGithub size={14} /> View on GitHub ↗
          </Link>
        </aside>
      </div>
    </article>
  );
}
